name: Robot Framework Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run Robot Framework tests
    - name: Run Robot Framework tests
      run: |
        robot --outputdir result tests/

    # Step 5: Upload the results as artifacts
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: robot-test-results
        path: result/  # Upload the 'result' directory containing the test results

    # Step 6: Optionally, you can print the test results in the log
    - name: Display Test Results
      run: |
        cat result/output.xml
