name: Robot Framework Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run Robot Framework tests
    - name: Run Robot Framework tests
      run: |
        robot --outputdir result tests/

    # Step 5: Upload the results as artifacts
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: robot-test-results
        path: result/  # Upload the 'result' directory containing the test results

    # - name: Publish Report to Jira
    #   # Create the Jira issue
    #   run: |
    #     curl -X POST \
    #       -H "Authorization: Basic $(echo -n "${{ secrets.JIRA_USERNAME }}:${{ secrets.JIRA_API_TOKEN }}" | base64)" \
    #       -H "Content-Type: application/json" \
    #       -d '{
    #         "fields": {
    #           "project": {
    #             "key": "TA"
    #           },
    #           "summary": "Test Report for Build #${{ github.run_id }}",
    #           "description": "Automated test results uploaded via GitHub Actions.",
    #           "issuetype": {
    #             "name": "Task"
    #           }
    #         }
    #       }' \
    #       "https://${{ secrets.JIRA_DOMAIN }}/rest/api/2/issue/"

    - name: Attach test report to Jira issue
      # Attach test report to existing Jira issue
      run: |
        ISSUE_KEY="TA-1"
        curl -u "${{ secrets.JIRA_USERNAME }}:${{ secrets.JIRA_API_TOKEN }}" \
        -X POST \
        -H "X-Atlassian-Token: no-check" \
        -F "file=@result/report.html" \
        -F "filename=report.html" \
        "https://${{ secrets.JIRA_DOMAIN }}/rest/api/2/issue/${ISSUE_KEY}/attachments"


    # Step 6: Optionally, you can print the test results in the log
    # - name: Display Test Results
    #   run: |
    #     cat result/output.xml
